version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/insiderguard
  frontend:
    build: ./frontend/insiderguard-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
  mongo:
    image: mongo
    ports:
      - "27017:27017"
